//! Action types: kinds and authorized actions.

use crate::error::AuraError;
use crate::ids::ActionId;
use bytes::Bytes;
use serde::{Deserialize, Serialize};

use super::ToolCall;

/// The kind of action (whitepaper-aligned).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionKind {
    /// Reasoning/thinking action
    Reason,
    /// Whitepaper placeholder — not yet generated by any production code path.
    /// Store information for future use
    Memorize,
    /// Whitepaper placeholder — not yet generated by any production code path.
    /// Make a decision
    Decide,
    /// Delegate to external system (tools, other agents)
    Delegate,
}

/// An authorized action to be executed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Action {
    /// Unique action identifier
    pub action_id: ActionId,
    /// Type of action
    pub kind: ActionKind,
    /// Versioned payload (opaque bytes)
    #[serde(with = "crate::serde_helpers::bytes_serde")]
    pub payload: Bytes,
}

impl Action {
    /// Create a new action.
    #[must_use]
    pub fn new(action_id: ActionId, kind: ActionKind, payload: impl Into<Bytes>) -> Self {
        Self {
            action_id,
            kind,
            payload: payload.into(),
        }
    }

    /// Create a delegate action for a tool call.
    ///
    /// # Errors
    /// Returns `AuraError::Serialization` if the tool call cannot be serialized.
    pub fn delegate_tool(tool_call: &ToolCall) -> Result<Self, AuraError> {
        let payload = serde_json::to_vec(tool_call)?;
        Ok(Self::new(
            ActionId::generate(),
            ActionKind::Delegate,
            payload,
        ))
    }
}
