// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPersona } from "./AgentPersona";

/**
 * "Who is this agent" bundle.
 */
export type AgentIdentity = { 
/**
 * Stable template agent UUID — the row in the `agents` table.
 * Used by the harness for skill / billing / permissions lookup
 * keyed on the template (not the partition).
 */
template_id: string | null, 
/**
 * Partitioned harness agent id, one of:
 * - `{template}::default`        (bare agent, no instance/session axis)
 * - `{template}::{instance}`     (per-instance partition)
 * - `{template}::{instance}::{session}` (per-(instance, session) partition)
 *
 * Used as the kernel turn-lock key + record-log partition;
 * absent ⇒ the harness mints a fresh `AgentId`.
 */
partition_id: string | null, 
/**
 * Persona fields rendered into the `<agent_identity>` section
 * of the assembled system prompt: name / role / personality.
 */
persona: AgentPersona | null, 
/**
 * Operator-curated skill names rendered as `<agent_skills>` in
 * the assembled system prompt. Empty ⇒ no skills section.
 */
skills: Array<string>, 
/**
 * Operator-authored system prompt (the "system prompt"
 * textarea on the agent template). Rendered as
 * `<agent_system_prompt>`. `None` or empty ⇒ no section
 * rendered.
 */
system_prompt: string | null, };
