// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledIntegration } from "./InstalledIntegration";
import type { InstalledTool } from "./InstalledTool";
import type { IntentClassifierSpec } from "./IntentClassifierSpec";

/**
 * "What tools / integrations / intent classifier the agent can use."
 *
 * Renamed from `capabilities` so the noun is qualified — a bare
 * `capabilities` would conflict visually with the
 * `aura_core_permissions::Capability` privilege enum.
 */
export type AgentCapabilities = { 
/**
 * Installed tools registered for this run.
 */
installed_tools: Array<InstalledTool>, 
/**
 * Installed integrations authorized for this run.
 */
installed_integrations: Array<InstalledIntegration>, 
/**
 * Optional keyword-driven intent classifier spec. When present
 * the harness narrows the per-turn tool surface based on each
 * user message.
 */
intent_classifier: IntentClassifierSpec | null, };
