// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledIntegration } from "./InstalledIntegration";
import type { InstalledTool } from "./InstalledTool";
import type { IntentClassifierSpec } from "./IntentClassifierSpec";

/**
 * "What tools / integrations / intent classifier the agent can use."
 *
 * Renamed from `capabilities` so the noun is qualified — a bare
 * `capabilities` would conflict visually with the
 * `aura_core_permissions::Capability` privilege enum.
 */
export type AgentCapabilities = { 
/**
 * Installed tools registered for this run.
 */
installed_tools: Array<InstalledTool>, 
/**
 * Installed integrations authorized for this run.
 */
installed_integrations: Array<InstalledIntegration>, 
/**
 * Optional keyword-driven intent classifier spec. When present
 * the harness narrows the per-turn tool surface based on each
 * user message.
 */
intent_classifier: IntentClassifierSpec | null, 
/**
 * Computer-use capability flag. When `true`, the harness exposes
 * the Anthropic computer-use tool for this run so the agent can
 * drive the real OS cursor/keyboard and read back screenshots.
 * Off by default; strictly additive (older producers omit it and
 * it deserializes to `false`).
 */
computer_use: boolean, 
/**
 * Base URL of the desktop computer-use executor the harness should
 * forward `computer` actions to (e.g.
 * `"http://127.0.0.1:<port>"`). `None` disables forwarding even
 * when [`Self::computer_use`] is set. Additive and omitted from
 * the wire when absent.
 */
computer_executor_url: string | null, };
