// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rendered text plus token estimate for a single context entry — one
 * tool, one skill, or one subagent kind.
 *
 * `tokens` uses the same `chars / CHARS_PER_TOKEN` heuristic as the
 * matching bucket in [`crate::server::ContextBreakdown`], so the
 * per-segment numbers stay directly comparable to the bucket total.
 */
export type ContextSegment = { 
/**
 * Short human-readable label (tool name, skill name, subagent kind).
 */
label: string, 
/**
 * Full rendered text the model receives for this entry.
 */
text: string, 
/**
 * Estimated token cost of [`Self::text`].
 */
tokens: bigint, };
