// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextSegment } from "./ContextSegment";

/**
 * Actual rendered text for each static context bucket, parallel to the
 * token counts in [`crate::server::ContextBreakdown`].
 *
 * - `system_prompt` — the full rendered system prompt (already
 *   includes any injected skill text). `None` when the prompt is
 *   empty.
 * - `tools` — one segment per tool the request would carry.
 * - `skills` — one segment per installed skill (name + summary).
 * - `subagents` — one segment per registered subagent kind.
 * - `mcp` — reserved for MCP server context; empty today, mirroring
 *   the zeroed `mcp_tokens` bucket.
 */
export type ContextContents = { system_prompt: string | null, tools: Array<ContextSegment>, skills: Array<ContextSegment>, subagents: Array<ContextSegment>, mcp: Array<ContextSegment>, };
