// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CouncilMemberRole } from "./CouncilMemberRole";
import type { ModelSelection } from "./ModelSelection";

/**
 * One member of an AURA Council run: a model to fan the shared query
 * out to. `id` is a stable per-member slot id the runtime echoes back
 * on the member's `SubagentSpawned` so the UI can correlate columns.
 */
export type CouncilMember = { 
/**
 * Stable member id (the council slot index as a string, e.g. "0").
 */
id: string, 
/**
 * Model driving this member.
 */
model: ModelSelection,
/**
 * Optional semantic role for specialized Council-backed flows.
 * Ordinary AURA Council requests omit this field. Second Opinion
 * stamps `aggregator` on the final-answer model and `reference` on
 * advisor models so newer runtimes can apply Hermes-style behavior,
 * while older runtimes ignore the unknown JSON field and keep using
 * the classic Council path.
 */
role: CouncilMemberRole | null, };
