// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional role for a [`CouncilMember`].
 */
export type CouncilMemberRole = "aggregator" | "reference";
