// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatProjectInfoWire } from "./ChatProjectInfoWire";

/**
 * "Which project + which billing partition."
 *
 * `None` on a [`RuntimeRequest`] means "no project" (ad-hoc chat).
 * `Some(...)` carries the project UUID, the optional typed
 * project descriptor consumed by the harness's
 * `SystemPromptBuilder.project_context()`, and the billing-header
 * values (`X-Aura-Org-Id`, `X-Aura-Session-Id`, `X-Aura-Agent-Id`)
 * the harness stamps on outbound `/v1/messages` calls.
 */
export type ProjectContext = { 
/**
 * Project UUID for domain tool calls (specs, tasks, etc.).
 */
project_id: string, 
/**
 * Typed project descriptor surfaced into the chat-path system
 * prompt's `<project_context>` section. `None` ⇒ no project
 * block rendered (bare-agent chat).
 */
project_info: ChatProjectInfoWire | null, 
/**
 * Organization UUID for `X-Aura-Org-Id` billing header.
 */
aura_org_id: string | null, 
/**
 * Storage session UUID for `X-Aura-Session-Id` billing header.
 */
aura_session_id: string | null, 
/**
 * Project-agent UUID for `X-Aura-Agent-Id` billing header.
 */
aura_agent_id: string | null, };
