// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-selected reasoning-effort tier carried end-to-end from the chat
 * model picker to the router.
 *
 * Provider-neutral **superset** — each model only exposes the subset it
 * supports (gated in the aura-os model catalog). Aura Router maps `Minimal`
 * to `none` for current OpenAI models; GPT-5.6 also exposes distinct `XHigh`
 * and `Max` tiers. Mirror of `aura_os::aura_protocol::ReasoningEffort` —
 * both copies of the wire contract must match.
 */
export type ReasoningEffort = "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
