// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `POST /v1/run`.
 */
export type RuntimeRunResponse = { 
/**
 * Stable identifier for the spawned run. Used as the path
 * segment on `WS /stream/:run_id` and on the lifecycle
 * endpoints (`/v1/run/:id/status`, `/v1/run/:id/pause`,
 * `/v1/run/:id/stop`).
 */
run_id: string, 
/**
 * Convenience field — the relative WS path the client should
 * open. Always `/stream/:run_id`; surfaced explicitly so older
 * clients don't have to know the path scheme.
 */
event_stream_url: string, };
