// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";

/**
 * Discriminated union carrying the data unique to each run type.
 *
 * One proper Rust enum — no separate `kind` discriminator + opaque
 * `kind_params` payload. The wire format uses
 * `serde(tag = "kind", content = "params", rename_all = "snake_case")`
 * so a `Chat` variant serializes as
 * `{"kind": "chat", "params": { conversation_messages: [...] }}`.
 */
export type RuntimeRequestType = { "kind": "chat", "params": { 
/**
 * Prior conversation messages to hydrate into session
 * history (empty for a brand-new session).
 */
conversation_messages: Array<ConversationMessage>, } } | { "kind": "dev_loop", "params": Record<string, never> } | { "kind": "task_run", "params": { 
/**
 * Task UUID the automaton should execute.
 */
task_id: string, 
/**
 * Retry warm-up: the reason text persisted on the previous
 * attempt's `task_failed` record, threaded into
 * `TaskInfo::execution_notes`.
 */
prior_failure: string | null, 
/**
 * Retry warm-up: recent work-log entries the agent should
 * re-see.
 */
work_log: Array<string>, } };
