// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * "Where the agent runs."
 *
 * `workspace` is the sandboxed directory under the harness's
 * `workspaces` base. `project_path` is the real project directory
 * on the host filesystem; when set, tool execution happens directly
 * against this directory instead of the sandbox.
 */
export type WorkspaceLocation = { 
/**
 * Workspace directory path (must be under the server's
 * `workspaces` base).
 */
workspace: string | null, 
/**
 * Absolute path to the real project directory on the host
 * filesystem.
 */
project_path: string | null, 
/**
 * Optional remote-git source URL for dev-loop / task-run
 * kickoffs.
 */
git_repo_url: string | null, 
/**
 * Optional remote-git branch paired with [`Self::git_repo_url`].
 */
git_branch: string | null, };
